name: Sync stocks integration

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * 4'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.6'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    # You can test your matrix by printing the current Python version
    - name: WB-MS sync stocks integration
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt;
        pip install -e ./libs/pymysklad
        pip install -e ./libs/pywb
    - name: Run wb photo integration job
      env:
        MS_TOKEN: ${{ secrets.MS_TOKEN }}
        WB_TOKEN_64: ${{ secrets.WB_TOKEN_64 }}
      run: python ./integrations/stocks_sync.py
